# Generated by Django 4.0.1 on 2022-01-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_order_being_delivered_remove_order_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='ordered',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'NEW'), ('C', 'CANCELLED'), ('R', 'REJECTED'), ('A', 'APPROVED')], default='N', help_text='Status Order', max_length=1),
        ),
    ]
