# Generated by Django 4.0.1 on 2022-02-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_orderproduct_ordered_orderproduct_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
