# Generated by Django 4.0.1 on 2022-02-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_orderproduct_customer_alter_customer_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='status',
        ),
    ]
